### PR TITLE
Fix matching of edit paths to original file paths on Windows

### LINKED ISSUE #3: Path separator mismatch on Windows
Hello @oprypin 🙂 
Still enjoying gen-files a lot!

I've just encountered the following issue on Windows (sorry, work...): gen-files warns me about files not existing.
It seems it's just a mismatch with path separators using backslashes on one side vs. forward slashes on the other:

```python
self._edit_paths: {
    'reference/package/index.md': 'src\\package\\__init__.py',
    ...
}
# while
page.file.src_path: 'reference\\package\\index.md'
```

...so this condition is always false:

https://github.com/oprypin/mkdocs-gen-files/blob/baf5a5e2ef0490fb2f9d2962c4edda66675a0a7d/mkdocs_gen_files/plugin.py#L44

I see that you are normalizing the path here:

https://github.com/oprypin/mkdocs-gen-files/blob/baf5a5e2ef0490fb2f9d2962c4edda66675a0a7d/mkdocs_gen_files/editor.py#L70

Maybe separators should not be replaced, or maybe the later comparison should wrap them in `Path` again or something.

What do you think?

### PR DESCRIPTION
**Pull request by oprypin**
Fixes #3

### CODE REVIEW

**Comment by oprypin** [comment]
Could you try it out and let me know if it works? @pawamoy

**Comment by pawamoy** [comment]
Yep, working fine! That's great, thanks 🙂

**Comment by pawamoy** [comment]
Could you release something like 0.3.4 🙏 🥺 ?

**Comment by oprypin** [comment]
Certainly. Don't know what I was even waiting for. It is done.

**Comment by pawamoy** [comment]
Thanks a lot :blush:

**Pull request merged**
